### ISSUE TITLE
Update to latest upstream version

### ISSUE THREAD

**Issue by eloo** [pkcakeout/pushgateway#2]
Hi,
are there any plans to update your version with the latest upstream changes?

Thanks in advance

**Comment by MrApplejuice** [comment]
Probably a good idea. I will give a try this weekend, hopefully there are not too many conflicts. Someone actually coded a default-timeout settings feature which I also want to pull.

**Comment by eloo** [comment]
okay.. sounds good to me.
Looking forward to test your new build ;)

**Comment by MrApplejuice** [comment]
Most of the upstream-fixes are merged. I just need to test everything again and bundle it in an updated docker image. I will do that later this week.

**Comment by eloo** [comment]
Thanks a lot. Nice to hear!
Close?

**Comment by MrApplejuice** [comment]
It has been done, the stale-timeout version of the pushgateway is a 0.4.0, which is also on docker-hub now: https://hub.docker.com/r/mrapplejuice/pushgateway/

Have fun, it should work as far as I was able to test it!

**Comment by eloo** [comment]
thanks.
will test it soon
